### ISSUE TITLE
Failed to export gems

### ISSUE THREAD

**Issue by luislavena** [rogerleite/rubygems_snapshot#1]
<pre><code>
$ gem snapshot export foo.yml --backtrace
ERROR:  While executing gem ... (NoMethodError)
    undefined method `end_with?' for "foo.yml":String
    /Library/Ruby/Gems/1.8/gems/rubygems_snapshot-0.1.2/lib/commands/snapshot_command.rb:139:in `get_and_check_arguments'
    /Library/Ruby/Gems/1.8/gems/rubygems_snapshot-0.1.2/lib/commands/snapshot_command.rb:30:in `execute'
    /Library/Ruby/Site/1.8/rubygems/command.rb:257:in `invoke'
    /Library/Ruby/Site/1.8/rubygems/command_manager.rb:132:in `process_args'
    /Library/Ruby/Site/1.8/rubygems/command_manager.rb:102:in `run'
    /Library/Ruby/Site/1.8/rubygems/gem_runner.rb:58:in `run'
    /usr/bin/gem:21
</code></pre>

Environment:

<pre><code>
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 1.3.5
  - RUBY VERSION: 1.8.6 (2008-08-11 patchlevel 287) [universal-darwin9.0]
  - INSTALLATION DIRECTORY: /Library/Ruby/Gems/1.8
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-9
  - GEM PATHS:
     - /Library/Ruby/Gems/1.8
     - /Users/luis/.gem/ruby/1.8
     - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :benchmark => false
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["http://gemcutter.org", "http://gems.github.com"]
     - "gem" => "--no-ri --no-rdoc"
  - REMOTE SOURCES:
     - http://gemcutter.org
     - http://gems.github.com
</code></pre>

**Comment by rogerleite** [comment]
The method end_with? doesn't exist in String from ruby 1.8.6 (http://ruby-doc.org/core/classes/String.html) :X
I had only tested with ruby 1.8.7 (http://ruby-doc.org/core-1.8.7/classes/String.html#M000743).

I'll correct this. Thanks for sharing!

**Comment by rogerleite** [comment]
New version 0.1.3, with ruby 1.8.6 compatibility.
Thanks again!
